package service

import (
	"bytes"
	"fmt"
	"log"

	"github.com/zyfdegh/hiupdate/server/entity"
	"github.com/zyfdegh/hiupdate/server/util"
)

// GetReport get report of a day
func GetReport(date string) (report *entity.Report, err error) {
	report = &entity.Report{}
	report.Title = "南京站会纪要"
	report.Date = date
	report.Weekday, err = util.GetWeekday(date)
	if err != nil {
		log.Printf("convert date to weekday error: %v", err)
		return
	}
	records, err := GetRecords(date)
	if err != nil {
		log.Printf("service get records error: %v", err)
		return
	}
	report.Records = records
	return report, nil
}

// ConvertText convert report as text file
func ConvertText(report entity.Report) (text string, err error) {
	var buf bytes.Buffer
	week, err := util.GetWeekday(report.Date)
	if err != nil {
		log.Printf("get weekday error: %v", err)
		return "", err
	}
	buf.WriteString(fmt.Sprintf("# %s 星期%s %s", report.Date, week, report.Title))
	for _, record := range report.Records {
		number := 1
		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("%d. %s\n", number, record.Person.Name))
		buf.WriteString(fmt.Sprintf("昨天: %s\n", number, record.Content.Done))
		buf.WriteString(fmt.Sprintf("今天: %s\n", number, record.Content.Todo))
		buf.WriteString(fmt.Sprintf("问题: %s\n", number, record.Content.Issue))
		number++
	}
	buf.WriteString("\n")
	buf.WriteString("* 以上顺序按照首次汇报日期排序\n")
	buf.WriteString("* This report is generated by hiupdate(github.com/zyfdegh/hiupdate).\n")
	return buf.String(), err
}
